# .goreleaser.yml
builds:
  - binary: pfxsigner
    goos:
      - darwin
      - linux
    goarch:
      - amd64

before:
  hooks:
  - make build

archives:
  - format: tar.gz
    files:
      - props.json.sample
      - README.md
      - LICENSE

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - pfxsigner
    image_templates:
    - "mrkaran/pfxsigner:latest"
    - "mrkaran/pfxsigner:{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile
    extra_files:
    - props.json.sample